Mutual_Funds_Families = [
    "Navi Mutual Fund",
    "SBI Mutual Fund",
    "Tata Mutual Fund",
    "Edelweiss Mutual Fund",
    "Bank of India Mutual Fund",
    "LIC Mutual Fund",
    "Sundaram Mutual Fund",
    "quant Mutual Fund",
    "Bandhan Mutual Fund",
    "DSP Mutual Fund",
    "Quantum Mutual Fund",
    "Angel One Mutual Fund",
    "Taurus Mutual Fund",
    "Jio BlackRock Mutual Fund",
    "Old Bridge Mutual Fund",
    "Baroda BNP Paribas Mutual Fund",
    "JM Financial Mutual Fund",
    "Canara Robeco Mutual Fund",
    "Bajaj Finserv Mutual Fund",
    "HDFC Mutual Fund",
    "HSBC Mutual Fund",
    "Invesco Mutual Fund",
    "Capitalmind Mutual Fund",
    "Trust Mutual Fund",
    "360 ONE Mutual Fund",
    "NJ Mutual Fund",
    "Mahindra Manulife Mutual Fund",
    "Groww Mutual Fund",
    "Zerodha Mutual Fund",
    "UTI Mutual Fund",
    "Unifi Mutual Fund",
    "ICICI Prudential Mutual Fund",
    "Franklin Templeton Mutual Fund",
    "PPFAS Mutual Fund",
    "WhiteOak Capital Mutual Fund",
    "Motilal Oswal Mutual Fund",
    "Shriram Mutual Fund",
    "Aditya Birla Sun Life Mutual Fund",
    "Kotak Mahindra Mutual Fund",
    "Samco Mutual Fund",
    "Helios Mutual Fund",
    "Mirae Asset Mutual Fund",
    "ITI Mutual Fund",
    "PGIM India Mutual Fund",
    "Nippon India Mutual Fund",
    "Axis Mutual Fund",
    "Union Mutual Fund"
]