"""create investments table

Revision ID: cd238383409f
Revises: 03dd0de8fc1e
Create Date: 2025-09-10 12:11:50.046557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd238383409f'
down_revision: Union[str, None] = '03dd0de8fc1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scheme_code', sa.Integer(), nullable=True),
    sa.Column('scheme_name', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('mutual_fund_family', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    # ### end Alembic commands ###
